explicitly include cstdint for gcc 13
Starting from gcc 13, it is required to explicitly include cstdint,
as other standard library header files will not include other headers
that were being used internally by the library. So update_engine also
has to explicitly include cstdint to avoid build errors like below:

```
./src/update_engine/install_plan.h:18:15: error: uint64_t has not been
declared
  ./src/update_engine/install_plan.h:10:1: note: uint64_t is defined in
header <cstdint>; did you forget to #include <cstdint>?
```